import type { Metadata } from "next";
import Link from "next/link";
import { Footer } from "@/components/landing/footer";
import { siteUrl } from "@/lib/site";

export const metadata: Metadata = {
  title: "Early Access Terms of Use",
  description:
    "Early Access Terms of Use for BimRoss LLC operating MakeACompany.ai and the Platform.",
  alternates: {
    canonical: "/terms",
  },
  openGraph: {
    title: "Early Access Terms of Use",
    description:
      "Early Access Terms of Use for BimRoss LLC operating MakeACompany.ai and the Platform.",
    url: `${siteUrl}/terms`,
  },
};

/** Lettered (a), (b)… lists */
function AlphaList({ items }: { items: string[] }) {
  return (
    <ul className="mt-2 list-none space-y-2 pl-0">
      {items.map((item, index) => (
        <li key={index} className="pl-0">
          <span className="font-medium tabular-nums">({String.fromCharCode(97 + index)})</span> {item}
        </li>
      ))}
    </ul>
  );
}

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-background">
      <section className="mx-auto w-full max-w-3xl px-6 py-16 sm:py-20">
        <p className="text-sm uppercase tracking-[0.16em] text-muted-foreground">Legal</p>
        <h1 className="mt-3 text-4xl font-semibold tracking-tight sm:text-5xl">Early Access Terms of Use</h1>
        <p className="mt-4 text-sm text-muted-foreground">Last updated: April 26, 2026</p>

        <div className="mt-10 space-y-8 text-base leading-7 text-foreground/90">
          <div className="space-y-3">
            <p>
              These Early Access Terms of Use are entered into between BimRoss LLC, a Wyoming limited liability
              company (&quot;Company&quot;, &quot;we&quot;, &quot;us&quot; or &quot;our&quot;), and the person or entity accessing or using the
              Platform (&quot;User&quot;, &quot;you&quot; or &quot;your&quot;).
            </p>
            <p>
              By clicking &quot;I Accept&quot;, creating an account, accessing the Platform, approving any Agent action,
              connecting any third-party account, or using any part of the Services, you agree to be bound by these
              Terms.
            </p>
            <p>
              If you are using the Services on behalf of an entity, you represent that you have authority to bind that
              entity, and references to &quot;you&quot; include that entity.
            </p>
          </div>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold">1. Definitions</h2>
            <div className="space-y-3">
              <p>
                <span className="font-semibold tabular-nums">1.1</span> &quot;Agents&quot; means any AI agents, assistants,
                workflows, automations, tools, models, prompts, software processes or related functionality made
                available through the Platform.
              </p>
              <p>
                <span className="font-semibold tabular-nums">1.2</span> &quot;Approval Record&quot; means any record generated
                or retained by us in connection with a user approval, including user identity, timestamp, action type,
                prompt, proposed Output, approval decision, relevant metadata and related logs.
              </p>
              <p>
                <span className="font-semibold tabular-nums">1.3</span> &quot;Content&quot; means any text, data, information,
                materials, prompts, instructions, documents, code, business plans, workflows, strategies, images,
                outputs, communications or other content submitted to, generated by, or made available through the
                Platform.
              </p>
              <p>
                <span className="font-semibold tabular-nums">1.4</span> &quot;Create Action&quot; means any Agent action,
                workflow, function or skill that creates, generates, configures, modifies, publishes, sends, deploys,
                submits, connects, triggers or otherwise produces any document, file, workflow, configuration,
                communication, output, system action or other result.
              </p>
              <p>
                <span className="font-semibold tabular-nums">1.5</span> &quot;Inputs&quot; means Content submitted, uploaded,
                connected, entered or otherwise provided by you.
              </p>
              <p>
                <span className="font-semibold tabular-nums">1.6</span> &quot;Outputs&quot; means Content generated, suggested,
                produced, configured or made available by the Platform or any Agent.
              </p>
              <p>
                <span className="font-semibold tabular-nums">1.7</span> &quot;Platform&quot; means the BimRoss, MakeACompany.ai
                and related websites, applications, APIs, tools, Agents, workflows, interfaces, documentation,
                integrations and services made available by us.
              </p>
              <p>
                <span className="font-semibold tabular-nums">1.8</span> &quot;Services&quot; means the early access services
                provided through the Platform, including AI-assisted business creation, business operations, workflow
                generation, automation, agent orchestration, research, execution support and related functionality.
              </p>
              <p>
                <span className="font-semibold tabular-nums">1.9</span> &quot;Third-Party Services&quot; means any third-party
                product, account, platform, service, API, model, software, payment provider, communications tool, cloud
                service, analytics provider, code repository, marketplace, hosting service or integration that interacts
                with or is connected to the Platform.
              </p>
            </div>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold">2. Early Access Nature Of The Services</h2>
            <p>
              <span className="font-semibold tabular-nums">2.1</span> The Services are provided as an early access, beta
              and experimental product.
            </p>
            <p>
              <span className="font-semibold tabular-nums">2.2</span> You acknowledge and agree that the Platform may be
              incomplete, unstable, inaccurate, unavailable, modified, restricted, suspended, discontinued or materially
              changed at any time.
            </p>
            <p>
              <span className="font-semibold tabular-nums">2.3</span> We do not represent or warrant that the Services are
              suitable for production use, commercial reliance, regulated activity, critical business operations, or any
              particular business purpose.
            </p>
            <p>
              <span className="font-semibold tabular-nums">2.4</span> You use the Services at your own risk.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold">3. Nature Of The Platform</h2>
            <p>
              <span className="font-semibold tabular-nums">3.1</span> The Platform is designed to assist users in
              creating, testing, launching, operating and scaling business concepts using AI-enabled tools and Agents.
            </p>
            <p>
              <span className="font-semibold tabular-nums">3.2</span> The Platform may generate or assist with business
              plans, product concepts, websites, workflows, communications, operational processes, sales materials,
              technical outputs, code, research, customer-facing materials and other business-related Content.
            </p>
            <p>
              <span className="font-semibold tabular-nums">3.3</span> The Platform does not provide legal, tax, financial,
              accounting, investment, medical, employment, regulatory or other professional advice.
            </p>
            <p>
              <span className="font-semibold tabular-nums">3.4</span> You are solely responsible for obtaining professional
              advice where appropriate.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold">4. User Responsibility And No Reliance</h2>
            <p>
              <span className="font-semibold tabular-nums">4.1</span> You are solely responsible for:
            </p>
            <AlphaList
              items={[
                "all Inputs you provide;",
                "all instructions, prompts, configurations and permissions you give to the Platform or any Agent;",
                "reviewing, validating and approving all Outputs;",
                "determining whether any Output is accurate, lawful, appropriate, complete and suitable for your intended use;",
                "all decisions made, actions taken, businesses created, communications sent, materials published, transactions entered into, and operations conducted using or in reliance on the Services; and",
                "compliance with all applicable laws, regulations, industry rules, platform terms and third-party rights.",
              ]}
            />
            <p>
              <span className="font-semibold tabular-nums">4.2</span> You must not rely on the Platform or any Output as a
              substitute for your own judgment, professional advice, human review or independent verification.
            </p>
            <p>
              <span className="font-semibold tabular-nums">4.3</span> We are not responsible for any business outcome,
              commercial result, loss, liability or consequence arising from your use of the Platform or any Output.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold">5. AI Agents And Autonomous Functionality</h2>
            <p>
              <span className="font-semibold tabular-nums">5.1</span> The Platform may enable Agents to generate,
              recommend, draft, configure, schedule, automate, connect, publish, send, submit, deploy or otherwise assist
              with actions on your behalf.
            </p>
            <p>
              <span className="font-semibold tabular-nums">5.2</span> Unless we expressly agree otherwise in writing,
              Agents are tools operated for your benefit and under your responsibility.
            </p>
            <p>
              <span className="font-semibold tabular-nums">5.3</span> You acknowledge that Agents may:
            </p>
            <AlphaList
              items={[
                "misunderstand instructions;",
                "produce inaccurate, incomplete, misleading, biased, unlawful, infringing or unsuitable Outputs;",
                "take or recommend actions that are commercially, legally or operationally inappropriate;",
                "fail to complete tasks;",
                "duplicate, conflict with, or interfere with other systems or workflows;",
                "interact unpredictably with Third-Party Services; and",
                "produce different results from the same or similar Inputs.",
              ]}
            />
            <p>
              <span className="font-semibold tabular-nums">5.4</span> You are responsible for monitoring all Agent activity
              and for implementing appropriate approval flows, limits, permissions and safeguards.
            </p>
            <p>
              <span className="font-semibold tabular-nums">5.5</span> The Platform is currently designed so that each
              Create Action requires affirmative user approval before it is performed, including Create Actions that
              generate documents, workflows, files, materials, configurations or other Outputs. You are responsible for
              reviewing the relevant proposed action, instruction, Output, workflow, document, configuration or other
              material before approving it. By approving any Agent action, you instruct and authorize the Platform and
              applicable Agent to perform that action, and you accept responsibility for the approved action and any
              resulting Output, workflow, record, communication, file, configuration or other consequence. We may record
              and retain Approval Records and may rely on them as evidence of your instruction and authorization.
            </p>
            <p>
              <span className="font-semibold tabular-nums">5.6</span> You must not enable any Agent to take externally
              binding, irreversible, regulated, financial, legal, customer-facing or material business action without
              appropriate human review and approval.
            </p>
            <p>
              <span className="font-semibold tabular-nums">5.7</span> We may impose, modify or remove limits, controls,
              permissions, approval requirements, throttles, suspensions or other safeguards at any time.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold">6. Third-Party Services And Connected Accounts</h2>
            <p>
              <span className="font-semibold tabular-nums">6.1</span> The Platform may allow you to connect or interact
              with Third-Party Services.
            </p>
            <p>
              <span className="font-semibold tabular-nums">6.2</span> By connecting a Third-Party Service, you authorize the
              Platform and applicable Agents to access, use, process, retrieve, transmit and act upon information from
              that Third-Party Service in accordance with your instructions, configurations and permissions.
            </p>
            <p>
              <span className="font-semibold tabular-nums">6.3</span> You are solely responsible for:
            </p>
            <AlphaList
              items={[
                "ensuring you have the right to connect and use each Third-Party Service;",
                "complying with all applicable third-party terms;",
                "managing permissions, credentials, API keys, access tokens and account settings;",
                "monitoring all activity conducted through connected accounts; and",
                "all fees, charges, losses, liabilities and consequences arising from connected Third-Party Services.",
              ]}
            />
            <p>
              <span className="font-semibold tabular-nums">6.4</span> We are not responsible for any Third-Party Service,
              including its availability, performance, security, accuracy, terms, fees, failures, changes or actions.
            </p>
            <p>
              <span className="font-semibold tabular-nums">6.5</span> We may disconnect, restrict or suspend any
              Third-Party Service integration at any time.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold">7. Accounts And Security</h2>
            <p>
              <span className="font-semibold tabular-nums">7.1</span> You must provide accurate account information and
              keep it up to date.
            </p>
            <p>
              <span className="font-semibold tabular-nums">7.2</span> You are responsible for maintaining the
              confidentiality of your login credentials and for all activity under your account.
            </p>
            <p>
              <span className="font-semibold tabular-nums">7.3</span> You must notify us immediately if you suspect
              unauthorized access, misuse, compromise or security vulnerability.
            </p>
            <p>
              <span className="font-semibold tabular-nums">7.4</span> We may suspend or restrict access if we reasonably
              suspect unauthorized use, security risk, misuse, breach of these Terms, or legal or operational risk.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold">8. Acceptable Use</h2>
            <p>
              <span className="font-semibold tabular-nums">8.1</span> You must not use the Platform or any Output:
            </p>
            <AlphaList
              items={[
                "for any unlawful, fraudulent, deceptive, harmful, exploitative or misleading purpose;",
                "to create, operate, promote or support any business, product, service or activity that violates applicable law;",
                "to infringe, misappropriate or violate intellectual property, privacy, publicity, confidentiality, contractual or other rights;",
                "to generate or distribute spam, phishing, scams, malware, spyware, unauthorized scraping, credential harvesting or harmful code;",
                "to impersonate any person or entity or misrepresent affiliation, sponsorship or endorsement;",
                "to make, automate or support decisions in regulated, high-impact or sensitive areas without all legally required safeguards, notices, consents, reviews and approvals;",
                "to provide professional advice unless appropriately qualified and legally authorized to do so;",
                "to operate financial services, gambling, healthcare, employment, housing, credit, insurance, legal services, securities, crypto, adult, weapons, political persuasion, or other regulated or sensitive businesses without our prior written consent and all required legal approvals;",
                "to bypass rate limits, safety controls, access controls, monitoring systems or usage restrictions;",
                "to reverse engineer, benchmark, scrape, copy, train on, or attempt to extract the Platform, Agents, models, prompts, system instructions, workflows, source code, architecture or underlying technology, except to the extent such restriction is prohibited by law; or",
                "in any way that could damage, disable, overburden, impair and compromise the Platform, any Third-Party Service, or any person or system.",
              ]}
            />
            <p>
              <span className="font-semibold tabular-nums">8.2</span> We may determine, in our sole discretion, whether any
              use is prohibited or creates unacceptable risk.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold">9. Inputs, Outputs And Ownership</h2>
            <p>
              <span className="font-semibold tabular-nums">9.1</span> As between you and us, you retain ownership of your
              Inputs.
            </p>
            <p>
              <span className="font-semibold tabular-nums">9.2</span> Subject to these Terms, we assign to you our right,
              title and interest, if any, in Outputs generated specifically for you through your use of the Platform.
            </p>
            <p>
              <span className="font-semibold tabular-nums">9.3</span> The assignment in clause 9.2 does not apply to:
            </p>
            <AlphaList
              items={[
                "the Platform;",
                "our technology, software, models, prompts, workflows, templates, methods, processes, know-how, documentation, interfaces, designs, systems, configurations, improvements or infrastructure;",
                "any pre-existing materials owned by us or our licensors;",
                "any generic, reusable or independently developed materials;",
                "any outputs generated for other users that are the same as or similar to your Outputs; or",
                "any Third-Party Services or third-party materials.",
              ]}
            />
            <p>
              <span className="font-semibold tabular-nums">9.4</span> You acknowledge that AI-generated outputs may not be
              unique, may be the same as or similar to outputs generated for other users, and may not be eligible for
              intellectual property protection in all jurisdictions.
            </p>
            <p>
              <span className="font-semibold tabular-nums">9.5</span> You are solely responsible for determining whether
              you can lawfully use, protect, commercialize, register or enforce rights in any Output.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold">10. Licence To Inputs And Usage Data</h2>
            <p>
              <span className="font-semibold tabular-nums">10.1</span> You grant us a worldwide, non-exclusive, royalty-free
              license to host, copy, process, transmit, display, disclose and use Inputs, Outputs and related data as
              necessary to provide, operate, secure, monitor, maintain, develop and improve the Services.
            </p>
            <p>
              <span className="font-semibold tabular-nums">10.2</span> We may use aggregated, anonymized or de-identified
              data for analytics, product improvement, benchmarking, research, reporting, security, operational and
              commercial purposes.
            </p>
            <p>
              <span className="font-semibold tabular-nums">10.3</span> Unless you expressly opt in or otherwise agree, we
              will not use your non-public Inputs to publicly identify you or disclose your confidential business idea to
              third parties for marketing purposes.
            </p>
            <p>
              <span className="font-semibold tabular-nums">10.4</span> You represent and warrant that you have all rights,
              consents, licenses and permissions necessary to provide your Inputs and to permit us to use them in
              accordance with these Terms.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold">11. Feedback</h2>
            <p>
              <span className="font-semibold tabular-nums">11.1</span> You may provide comments, suggestions, ideas,
              requests, bug reports, improvements or other feedback regarding the Platform.
            </p>
            <p>
              <span className="font-semibold tabular-nums">11.2</span> You grant us a perpetual, irrevocable, worldwide,
              royalty-free, transferable and sub-licensable license to use, exploit, commercialize, modify and incorporate
              feedback for any purpose without restriction or compensation.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold">12. Confidentiality</h2>
            <p>
              <span className="font-semibold tabular-nums">12.1</span> Each party may receive non-public information from
              the other party that is identified as confidential or should reasonably be understood to be confidential.
            </p>
            <p>
              <span className="font-semibold tabular-nums">12.2</span> Each party must use the other party&apos;s confidential
              information only for purposes connected with the Services and must take reasonable steps to protect it from
              unauthorized disclosure.
            </p>
            <p>
              <span className="font-semibold tabular-nums">12.3</span> Confidential information does not include
              information that is publicly available, already known without restriction, independently developed, or
              lawfully obtained from a third party.
            </p>
            <p>
              <span className="font-semibold tabular-nums">12.4</span> We may disclose confidential information to our
              personnel, contractors, service providers, professional advisers and infrastructure providers where
              reasonably necessary to provide, secure, improve or support the Services.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold">13. Privacy And Data Protection</h2>
            <p>
              <span className="font-semibold tabular-nums">13.1</span> Our collection, use and disclosure of personal
              information is governed by our{" "}
              <Link href="/privacy" className="underline underline-offset-4">
                Privacy Policy
              </Link>
              .
            </p>
            <p>
              <span className="font-semibold tabular-nums">13.2</span> You must not provide personal information to the
              Platform unless you have all necessary rights, notices, consents and lawful bases to do so.
            </p>
            <p>
              <span className="font-semibold tabular-nums">13.3</span> You are solely responsible for determining whether
              your use of the Platform complies with applicable data protection, privacy, marketing, employment, consumer
              protection and electronic communications laws.
            </p>
            <p>
              <span className="font-semibold tabular-nums">13.4</span> You must not submit sensitive personal information,
              regulated data, payment card data, protected health information, government identifiers or other high-risk
              data unless we have expressly agreed in writing that the Platform is suitable for that use.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold">14. Fees</h2>
            <p>
              <span className="font-semibold tabular-nums">14.1</span> The Services may be provided free of charge during
              early access or subject to fees notified to you.
            </p>
            <p>
              <span className="font-semibold tabular-nums">14.2</span> We may introduce, change or remove fees, usage
              limits, credits, plans or commercial terms at any time.
            </p>
            <p>
              <span className="font-semibold tabular-nums">14.3</span> You are responsible for all third-party fees, usage
              charges, infrastructure costs, model costs, payment processing charges and other external costs incurred
              through your connected accounts or use of Third-Party Services.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold">15. No Business, Revenue Or Investment Guarantee</h2>
            <p>
              <span className="font-semibold tabular-nums">15.1</span> We do not guarantee that use of the Platform will
              result in any company, product, customer, revenue, profit, funding, valuation, growth, sale, exit or other
              business outcome.
            </p>
            <p>
              <span className="font-semibold tabular-nums">15.2</span> Any examples, demos, projections, roadmaps, case
              studies, benchmarks or illustrations are provided for informational purposes only and are not guarantees or
              commitments.
            </p>
            <p>
              <span className="font-semibold tabular-nums">15.3</span> You are solely responsible for all commercial,
              operational, legal, financial and strategic decisions relating to any business created, tested, launched or
              operated using the Platform.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold">16. Platform Changes And Availability</h2>
            <p>
              <span className="font-semibold tabular-nums">16.1</span> We may modify, suspend, discontinue, replace, limit
              or remove all or part of the Platform or Services at any time.
            </p>
            <p>
              <span className="font-semibold tabular-nums">16.2</span> We do not guarantee that the Platform will be
              uninterrupted, secure, available, accurate, error-free or compatible with any system or Third-Party Service.
            </p>
            <p>
              <span className="font-semibold tabular-nums">16.3</span> We may conduct maintenance, updates, experiments,
              migrations, resets, deletions or changes that affect your account, workflows, Agents, Outputs or data.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold">17. Suspension And Termination</h2>
            <p>
              <span className="font-semibold tabular-nums">17.1</span> We may suspend, restrict or terminate your access to
              the Platform, any Agent, any workflow, any integration, or any Output at any time where we believe that:
            </p>
            <AlphaList
              items={[
                "you have breached these Terms;",
                "your use creates legal, regulatory, security, operational, reputational or commercial risk;",
                "your use may harm us, another user, a third party, a Third-Party Service, or the Platform;",
                "suspension is required by law, regulator, service provider or infrastructure provider; or",
                "continued access is inappropriate for an early access environment.",
              ]}
            />
            <p>
              <span className="font-semibold tabular-nums">17.2</span> You may stop using the Platform at any time.
            </p>
            <p>
              <span className="font-semibold tabular-nums">17.3</span> Upon termination, your right to access and use the
              Platform ceases immediately.
            </p>
            <p>
              <span className="font-semibold tabular-nums">17.4</span> Clauses intended by their nature to survive
              termination will survive, including clauses relating to ownership, data, feedback, confidentiality,
              disclaimers, liability, indemnity and governing law.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold">18. Disclaimers</h2>
            <p>
              <span className="font-semibold tabular-nums">18.1</span> To the maximum extent permitted by law, the
              Platform, Services, Agents and Outputs are provided on an &quot;as is&quot;, &quot;as available&quot; and &quot;with all
              faults&quot; basis.
            </p>
            <p>
              <span className="font-semibold tabular-nums">18.2</span> We disclaim all warranties, representations,
              conditions and guarantees, whether express, implied, statutory or otherwise, including any warranties of
              merchantability, fitness for a particular purpose, title, non-infringement, accuracy, availability,
              security, reliability, performance, suitability, uninterrupted operation, or that any Output will be lawful,
              correct, complete, useful or appropriate.
            </p>
            <p>
              <span className="font-semibold tabular-nums">18.3</span> You acknowledge that AI systems are probabilistic
              and may generate inaccurate, incomplete, misleading, offensive, non-compliant, infringing or otherwise
              unsuitable Outputs.
            </p>
            <p>
              <span className="font-semibold tabular-nums">18.4</span> You are solely responsible for human review,
              professional review, testing, validation and approval before using any Output externally or commercially.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold">19. Limitation Of Liability</h2>
            <p>
              <span className="font-semibold tabular-nums">19.1</span> To the maximum extent permitted by law, we are not
              liable for any:
            </p>
            <AlphaList
              items={[
                "loss of profits, revenue, business, opportunity, goodwill, reputation, anticipated savings, data or use;",
                "business interruption;",
                "failed launch, failed company, failed product, failed campaign or failed commercial outcome;",
                "loss arising from any Output, Agent action, integration, Third-Party Service, connected account, user instruction, user configuration, user approval, Create Action, Approval Record or business decision;",
                "indirect, consequential, incidental, special, exemplary or punitive damages; or",
                "matter outside our reasonable control.",
              ]}
            />
            <p>
              <span className="font-semibold tabular-nums">19.2</span> To the maximum extent permitted by law, our
              aggregate liability arising out of or in connection with these Terms, the Platform, the Services, Agents or
              Outputs is limited to the greater of:
            </p>
            <AlphaList
              items={[
                "the amounts paid by you to us for the Services in the three months before the event giving rise to liability; and",
                "USD 100.",
              ]}
            />
            <p>
              <span className="font-semibold tabular-nums">19.3</span> The limitations and exclusions in this clause apply
              whether the claim arises in contract, tort, negligence, statute, equity, misrepresentation, restitution or
              otherwise, even if we have been advised of the possibility of such loss.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold">20. Indemnity</h2>
            <p>
              <span className="font-semibold tabular-nums">20.1</span> You must indemnify, defend and hold harmless us,
              our affiliates, officers, directors, employees, contractors, agents, licensors and service providers from
              and against all claims, losses, liabilities, damages, penalties, fines, costs and expenses, including
              reasonable legal fees, arising out of or relating to:
            </p>
            <AlphaList
              items={[
                "your use of the Platform, Services, Agents or Outputs;",
                "your Inputs;",
                "any business, product, service, company, communication, transaction, workflow, campaign, integration or operation created, launched, supported or conducted using the Platform;",
                "any Agent action, Create Action, Approval Record, Output, user instruction, user configuration or user approval;",
                "your breach of these Terms;",
                "your breach of applicable law, regulation, third-party terms or third-party rights;",
                "any allegation that your Inputs or use of Outputs infringes or violates any rights of a third party; or",
                "any Third-Party Service connected to or used with your account.",
              ]}
            />
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold">21. Publicity</h2>
            <p>
              <span className="font-semibold tabular-nums">21.1</span> You must not publicly state or imply that we
              endorse, sponsor, approve, verify or are responsible for any business, product, service or Output created
              using the Platform without our prior written consent.
            </p>
            <p>
              <span className="font-semibold tabular-nums">21.2</span> We may identify you as an early access user only
              with your prior consent, unless otherwise permitted by law or agreed separately.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold">22. Export, Sanctions And Compliance</h2>
            <p>
              <span className="font-semibold tabular-nums">22.1</span> You must not use the Platform in violation of
              applicable export controls, sanctions, trade restrictions or anti-corruption laws.
            </p>
            <p>
              <span className="font-semibold tabular-nums">22.2</span> You represent that you are not located in,
              organized under the laws of, or ordinarily resident in any country or territory subject to comprehensive
              sanctions, and are not a restricted, sanctioned or prohibited party.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold">23. Changes To These Terms</h2>
            <p>
              <span className="font-semibold tabular-nums">23.1</span> We may update these Terms from time to time.
            </p>
            <p>
              <span className="font-semibold tabular-nums">23.2</span> If we make material changes, we may provide notice
              through the Platform, by email, or by requiring acceptance of updated terms.
            </p>
            <p>
              <span className="font-semibold tabular-nums">23.3</span> Your continued use of the Platform after updated
              Terms become effective constitutes acceptance of those Terms.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold">24. Governing Law And Disputes</h2>
            <p>
              <span className="font-semibold tabular-nums">24.1</span> These Terms are governed by the laws of the State of
              Wyoming, without regard to conflict of law principles.
            </p>
            <p>
              <span className="font-semibold tabular-nums">24.2</span> The courts located in the State of Wyoming have
              exclusive jurisdiction over any dispute arising out of or in connection with these Terms, unless we elect
              to seek injunctive or equitable relief in any competent jurisdiction.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold">25. Miscellaneous</h2>
            <p>
              <span className="font-semibold tabular-nums">25.1</span> You may not assign or transfer these Terms without
              our prior written consent.
            </p>
            <p>
              <span className="font-semibold tabular-nums">25.2</span> We may assign, transfer or novate these Terms in
              connection with a merger, acquisition, reorganization, financing, sale of assets, change of control,
              corporate restructuring or transfer of the Platform.
            </p>
            <p>
              <span className="font-semibold tabular-nums">25.3</span> These Terms constitute the entire agreement between
              the parties regarding the Services and supersede all prior discussions, proposals and understandings
              relating to the Services.
            </p>
            <p>
              <span className="font-semibold tabular-nums">25.4</span> If any provision of these Terms is held invalid or
              unenforceable, the remaining provisions remain in full force and effect.
            </p>
            <p>
              <span className="font-semibold tabular-nums">25.5</span> No failure or delay in enforcing any provision is
              a waiver.
            </p>
            <p>
              <span className="font-semibold tabular-nums">25.6</span> Nothing in these Terms creates any partnership,
              joint venture, employment, agency, fiduciary or franchise relationship.
            </p>
          </section>
        </div>
      </section>
      <Footer />
    </main>
  );
}
